name: Publish Python 🐍 package

on:
  push:
    tags:
      - "v*.*.*"   # push version example v0.1.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # for Trusted Publisher
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
